[package]
name = "desktidy"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
comfy-table = "7.1"
md5 = "0.7"
once_cell = "1.19"
owo-colors = "4"
regex = "1"
sha2 = "0.10"

[dev-dependencies]
insta = "1.38"
tempfile = "3"
